# Generated by Django 3.1.7 on 2021-03-26 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22, null=True, verbose_name='latitude')),
                ('available', models.BooleanField(default=False, verbose_name='available')),
                ('order_taken', models.BooleanField(default=False, verbose_name='order taken')),
                ('area', models.CharField(default='', max_length=60, verbose_name='area name')),
                ('city', models.CharField(default='', max_length=60, verbose_name='city name')),
                ('state', models.CharField(default='', max_length=60, verbose_name='state name')),
                ('country', models.CharField(default='', max_length=60, verbose_name='country name')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
