# Generated by Django 3.1.7 on 2021-03-26 12:40

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22, verbose_name='latitude')),
                ('available', models.BooleanField(default=True, verbose_name='available')),
                ('street', models.CharField(default='', max_length=60, verbose_name='street name')),
                ('area', models.CharField(default='', max_length=60, verbose_name='area name')),
                ('city', models.CharField(default='', max_length=60, verbose_name='city name')),
                ('state', models.CharField(default='', max_length=60, verbose_name='state name')),
                ('country', models.CharField(default='', max_length=60, verbose_name='country name')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('available', models.BooleanField(verbose_name='available')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='cost')),
                ('offer', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='offer')),
                ('major_category', models.CharField(max_length=60, verbose_name='major category')),
                ('minor_category', models.CharField(max_length=60, verbose_name='minor category')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel')),
            ],
        ),
    ]
